# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c53e0e40a8570ee1fcab66049926b353673f3ad9f52ecb7cfaff1e22a173e27d46b4f9270aacbb9017a09928c46fbd1d237a52c52b6731ec75206a9d1602d886

test:
  secret_key_base: 1934753283b6508e7c245f3fccc11a79fc9b623c28d5c28cde84ec5cc36a0469d4578c1137abe448649be8db5bdc85fa040d83809b0a6a35373106ba7702215f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
